LOOP-1492: support therapy settings max bolus
tidepool-org/Loop pull request #159
Opened 2020-07-15 23:54 UTC by rickpasetto

2020-07-16 01:23 UTC, mpangburn commented on Loop/Views/SettingsViewModel.swift
> +    let supportedBolusVolumes: [Double]?
Same note here as in my comment on https://github.com/tidepool-org/LoopKit/pull/147 re combining the optional properties since they're tied together

2020-07-16 14:49 UTC, novalegra requested changes

2020-07-16 14:49 UTC, novalegra commented on Loop/Views/SettingsView.swift
> +                                          supportedBolusVolumes: nil,
Same comment as on #158 about getting this value from the pumpManager or view model

2020-07-17 01:24 UTC, novalegra approved these changes

2020-07-17 03:13 UTC, mpangburn commented on Loop/View Controllers/SettingsTableViewController.swift
> +        let pumpSupportedIncrements = dataManager.pumpManager.map { PumpSupportedIncrements(basalRates: $0.supportedBasalRates, bolusVolumes: $0.supportedBolusVolumes) }
`map` strikes again! 🗺😎

2020-07-17 03:14 UTC, mpangburn approved these changes
LGTM!

2020-07-17 16:40 UTC, merged