LOOP-1680: Fix acknowledgement of repeating alerts
tidepool-org/Loop pull request #189
Opened 2020-07-31 18:15 UTC by rickpasetto

Basically, we shouldn't be removing pending UNs upon acknowledgement.  That was a 1-line change, but I also did some refactoring that I'd meant to do a while ago.

https://tidepool.atlassian.net/browse/LOOP-1680

2020-07-31 18:16 UTC, rickpasetto commented on Loop/Managers/Alerts/AlertManager.swift
> -        userNotificationCenter.removePendingNotificationRequests(withIdentifiers: [identifier.value])
This line "removePendingNotificationRequests" was removed, but only after being moved below...

2020-07-31 18:16 UTC, rickpasetto commented on Loop/Managers/Alerts/UserNotificationAlertPresenter.swift
> +            self.userNotificationCenter.removeDeliveredNotifications(withIdentifiers: [identifier.value])
... to here.

2020-07-31 19:27 UTC, nhamming approved these changes
LGTM

2020-08-03 19:48 UTC, ps2 requested changes
In general looks good; I haven't tested, but QA should be able to test this. I think there is some code that should be deleted, though.

2020-08-03 19:48 UTC, ps2 commented on Loop/Managers/Alerts/UserNotificationAlertPresenter.swift
> +        userNotificationContent.userInfo[AlertUserNotificationUserInfoKey.alertTimestamp.rawValue] =
I don't believe `userInfo[AlertUserNotificationUserInfoKey.alert.rawValue]` or `userInfo[AlertUserNotificationUserInfoKey.alert.rawValue]` are being used anywhere and can be removed, along with the alert string encoding methods.

2020-08-03 21:24 UTC, ps2 commented
Is there anything using the encodeToString and decode(from string) methods anymore or can those be removed too?

2020-08-03 21:37 UTC, rickpasetto commented
@ps2 Looks like they are not used, but they are also in LoopKit.  I don't feel strongly about removing them, since they seem like generally useful functions (and they are unit tested), but I'll put up a PR to remove if you feel strongly.

2020-08-03 21:40 UTC, ps2 commented
I usually have strong, happy feelings about removing code. :) I think it'd be a good idea, but isn't a huge priority.  It's code debt to leave it there.

2020-08-03 21:40 UTC, ps2 approved these changes
LGTM! Thanks!

2020-08-03 21:56 UTC, rickpasetto commented
@ps2 Actually, while those functions are no longer used by this code, they are used by unit tests to test the `Codable` implementation which _is_ used elsewhere.  I think they're small and simple enough functions to be relatively harmless there in

2020-08-03 22:07 UTC, ps2 commented
Why would tests for Codable conformance use a custom string encoding?

Also, looks like `timestampFormatter` is no longer used either?

2020-08-03 22:32 UTC, rickpasetto commented
@ps2 Custom? They just use JSON.  I could make it a bit cleaner by putting the extension into the tests instead... I'll do that.  See https://github.com/tidepool-org/LoopKit/pull/197

2020-08-04 15:49 UTC, ps2 approved these changes
I still don't understand why testing Codable conformance requires a separate encoding that isn't used in the main code, but maybe it's not important. Moving it into tests does help with the kruft aspect, as no-one will confuse it for the actual used encoding, so thanks!

2020-08-04 17:34 UTC, merged