Diy sync
tidepool-org/Loop pull request #24
Opened 2019-09-12 00:46 UTC by ps2

2019-09-12 16:24 UTC, nhamming approved these changes
Otherwise looks good.

2019-09-12 16:24 UTC, nhamming commented on Learn/Models/TimeComponents.swift
> +        if hour >= 24, minute >= 60 {
What about negative values?

2019-09-12 16:24 UTC, nhamming commented on Common/Models/PumpManagerUI.swift
> +        return nil
nit: this `guard` style seems different that what I usually see.

2019-09-12 16:24 UTC, nhamming commented on Common/Models/WatchContext.swift
nit: Is the common style to include `{` and `}` on the same line in this case?

2019-09-12 16:24 UTC, nhamming commented on Loop/Managers/NightscoutDataManager.swift
> +            symbol = nil
Will the `name` be displayed? If yes, should the predefined "Workout" and "PreMeal" be localized?

2019-09-12 16:24 UTC, nhamming commented on Loop/Managers/NightscoutDataManager.swift
> +            symbol = nil
Should the `name` be set from an `enum`?

2019-09-12 16:24 UTC, nhamming commented on Loop/Managers/StatusExtensionDataManager.swift
> +            {
nit: different `{` style

2019-09-12 16:24 UTC, nhamming commented on Loop/Models/StatusExtensionContext+LoopKit.swift
> +//    }
Why keep this code?

2019-09-12 16:24 UTC, nhamming commented on Loop/de.lproj/Localizable.strings
In these cases, would it not be better to just define this once in the default `.strings` such that it can be used when the value isn't found in other `.strings` files. At least I believe this is how the localized strings work. Might reduce any copy and paste errors.

2019-09-12 21:14 UTC, ps2 commented on Learn/Models/TimeComponents.swift
> +        if hour >= 24, minute >= 60 {
I generally don't do defensive programming for internal inputs. This was an exception to catch some math I was unsure about.

2019-09-12 21:15 UTC, ps2 commented on Common/Models/PumpManagerUI.swift
> +        return nil
Are you asking about the curly brace placement?

2019-09-12 21:16 UTC, ps2 commented on Common/Models/WatchContext.swift
yeah, usually

2019-09-12 21:41 UTC, ps2 commented on Loop/Managers/StatusExtensionDataManager.swift
> +            {
If there are multiline guard or ifs, I like having the { on a separate line for readability.  We can talk about this if it seems harmful.

2019-09-12 22:59 UTC, ps2 commented on Loop/de.lproj/Localizable.strings
Sure. It's questionable if this string should be localized, but someone did provide a russian translation so 🤷‍♂

2019-09-12 23:18 UTC, darinkrauss requested changes
A number of comments, but only one that I have any real concern about regarding the retrospective correction settings.

2019-09-12 23:18 UTC, darinkrauss commented on Cartfile.resolved
> +github "LoopKit/MKRingProgressView" "f548a5c64832be2d37d7c91b5800e284887a2a0a"
Why/how does `Cartfile.resolved` have "LoopKit/MKRingProgressView", but that isn't included in the `Cartfile`?

2019-09-12 23:18 UTC, darinkrauss commented on Common/Models/PumpManagerUI.swift
> +        return nil
FWIW, I usually use variable/constant names that match the rawValue property name. If the value is a rawValue/rawState itself, then I add that as its suffix. So, something like:

```
        let managerIdentifier = rawValue["managerIdentifier"] as? String,
        let hudProviderViewsRawState = rawValue["hudProviderViews"] as? HUDProvider.HUDViewsRawState,
        let manager = pluginManager.getPumpManagerTypeByIdentifier(managerIdentifier) ?? staticPumpManagersByIdentifier[managerIdentifier] as? PumpManagerUI.Type else
```

This is just my way to keep things more readable.

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        dateIntervalEntry = DateIntervalEntry(
[nit] Use `self.dateIntervalEntry` rather than just `dataIntervalEntry`?

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +            // TODO: Cleaner error presentation
[nit] TODO

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +fileprivate extension TextCell {
?

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        guard count > 0 else {
[nit] Personally, I'd put the `let` inside the guard, but tomEHtoes, tomAtoes...

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        guard let time = TimeComponents(dateComponents: date) else {
[nit] FWIW, I'd switch `date` -> `dateComponents` and `time` -> `date` just to be clearer.

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        guard let time = TimeComponents(dateComponents: date) else {
Same switch with `time` -> `dateComponents` in above function.

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +    typealias ResultType = ModalDayBuilder
Not sure I understand the purpose of this `typealias`. Why not just use `ModalDayBuilder` outright?

2019-09-12 23:18 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        os_log(.default, log: log, "Computing Modal day in %{public}@", String(describing: calculator.dates))
For the os log, are we using `OSLog` or `os_log`? I've seen a mix throughout. Would be good to standardize on one.

2019-09-12 23:18 UTC, darinkrauss commented on Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
> -               BuildableName = "Merge Feature Flags"
No more merging feature flags or is that now handled elsewhere?

2019-09-12 23:18 UTC, darinkrauss commented on Loop/Managers/DeviceDataManager.swift
> +            // No longer used...
No longer use just here? Or is the `willRequest` parameter now deprecated?

2019-09-12 23:18 UTC, darinkrauss commented on Loop/Managers/LoopDataManager.swift
> +        retrospectiveCorrection = settings.enabledRetrospectiveCorrectionAlgorithm
Perhaps a naive questions, but since this is now "cached" in the `LoopDataManager`, what happens if this is changed in the settings? How does the `LoopDataManager` pick up the new settings?

2019-09-12 23:18 UTC, darinkrauss commented on Loop/Models/NetBasal.swift
> +fileprivate let defaultMaxBasalForScale = 3.0
I'd make the `maxBasal` parameters below not optional and then this can go away.

Then the question becomes when can the `settings.maximumBasalRatePerHour` ever be nil?

2019-09-12 23:18 UTC, darinkrauss commented on Loop/Models/RetrospectiveCorrection/RetrospectiveCorrection.swift
> +    ///   - glucose: Most recent glucose
Comments need update here.

2019-09-12 23:18 UTC, darinkrauss commented on Loop/View Controllers/BolusViewController+LoopDataManager.swift
> +            print("BolusViewController: recommendation = \(String(describing: bolusRecommendation))")
Debug statement or use a logger?

2019-09-12 23:18 UTC, darinkrauss commented on Loop/View Controllers/PredictionTableViewController.swift
> -            let cell = tableView.dequeueReusableCell(withIdentifier: SwitchTableViewCell.className, for: indexPath) as! SwitchTableViewCell
Is this ditching the ability to turn off retrospective correction?

2019-09-12 23:18 UTC, darinkrauss commented on WatchApp Extension/Controllers/BolusInterfaceController.swift
> +        let maxBolusValue: Double = ExtensionDelegate.shared().loopManager.settings.maximumBolus ?? 10
Again, should `maximumBolus` ever be nil?

2019-09-13 14:34 UTC, ps2 commented on Cartfile.resolved
> +github "LoopKit/MKRingProgressView" "f548a5c64832be2d37d7c91b5800e284887a2a0a"
Cruft. Will remove.

2019-09-13 14:40 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +        guard count > 0 else {
The guard can only do a let from an optional.  But the bigger question is: toe meh toes?

2019-09-13 14:44 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +        dateIntervalEntry = DateIntervalEntry(
prefer leaving off self when there aren't any local vars with the same name.

2019-09-13 14:44 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +            // TODO: Cleaner error presentation
leaving this for now

2019-09-13 14:44 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +fileprivate extension TextCell {
removing

2019-09-13 14:44 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +        guard let time = TimeComponents(dateComponents: date) else {
prefer as is

2019-09-13 14:49 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +    typealias ResultType = ModalDayBuilder
will cleanup

2019-09-13 14:50 UTC, ps2 commented on Learn/Lessons/ModalDayLesson.swift
> +        os_log(.default, log: log, "Computing Modal day in %{public}@", String(describing: calculator.dates))
OSLog is the class, and os_log is the logging function

2019-09-13 14:53 UTC, ps2 commented on Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
> -               BuildableName = "Merge Feature Flags"
Feature flags are managed via SWIFT_ACTIVE_COMPILATION_CONDITIONS, which can be overridden in the workspace xcconfig.

2019-09-13 14:54 UTC, ps2 commented on Loop/Managers/DeviceDataManager.swift
> +            // No longer used...
No longer used here, but considering removing it as a pumpManager requirement altogether.

2019-09-13 14:57 UTC, ps2 commented on Loop/Managers/LoopDataManager.swift
> +        retrospectiveCorrection = settings.enabledRetrospectiveCorrectionAlgorithm
It's hardcoded now. This is to support IRC with an easy switch, but that inclusion is looking less likely now.

2019-09-13 15:00 UTC, ps2 commented on Loop/Models/NetBasal.swift
> +fileprivate let defaultMaxBasalForScale = 3.0
It's not set when the user has not defined it in settings.

2019-09-13 15:06 UTC, ps2 commented on Loop/View Controllers/BolusViewController+LoopDataManager.swift
> +            print("BolusViewController: recommendation = \(String(describing: bolusRecommendation))")
removed

2019-09-13 15:07 UTC, ps2 commented on Loop/View Controllers/PredictionTableViewController.swift
> -            let cell = tableView.dequeueReusableCell(withIdentifier: SwitchTableViewCell.className, for: indexPath) as! SwitchTableViewCell
Yes, as planned. I believe this is documented in our changes from DIY document.

2019-09-13 15:08 UTC, ps2 commented on WatchApp Extension/Controllers/BolusInterfaceController.swift
> +        let maxBolusValue: Double = ExtensionDelegate.shared().loopManager.settings.maximumBolus ?? 10
If the user has not set a max bolus in settings.

2019-09-13 20:30 UTC, darinkrauss commented on Loop/Models/NetBasal.swift
> +fileprivate let defaultMaxBasalForScale = 3.0
Ah, okay.

2019-09-13 20:33 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        guard count > 0 else {
Doh! Right. Remnants from Golang (where you can define any type of variable inside if statements).

Meh?

2019-09-13 20:36 UTC, darinkrauss commented on Learn/Lessons/ModalDayLesson.swift
> +        os_log(.default, log: log, "Computing Modal day in %{public}@", String(describing: calculator.dates))
Sorry, right. What I meant was using the `OSLog` extensions defined in `OSLog.swift`  so you could have:

```
log.default("Computing Modal day in %{public}@", String(describing: calculator.dates))
```

2019-09-13 20:43 UTC, darinkrauss approved these changes
LGTM! :shipit:

The only thing I'd like to get some clarification on for the future is which form of the log statement should be standardize on:

```
os_log(.default, log: log, ...
```

or

```
log.default(...
```

where `log` is an instance of `OSLog` in both cases and the latter case is enabled by an extension to `OSLog`.

2019-09-16 15:29 UTC, merged