COASTAL-668: Fix crash when alert acknowledgement fails
tidepool-org/Loop pull request #502
Opened 2022-03-22 21:20 UTC by rickpasetto

If alert acknowledgement fails, we display another in-app modal alert but need to do so on the main queue.

https://tidepool.atlassian.net/browse/COASTAL-668

2022-03-23 11:17 UTC, nhamming commented
@rickpasetto so what happens to the alert that the user confirmed but the pump manager was not able to pass that confirmation to the pump? I suspect we need additional code (likely in the pump manager) for pumps that require that user confirmation.

2022-03-23 19:18 UTC, rickpasetto commented
@nhamming This fix does not affect that behavior, only the crash that happens due to possibly being on the wrong queue (COASTAL-668).  To answer your question, I believe @ps2 was the one who added the ability for Alert acknowledgement to fail with this error.  The Alert facility does not "re-try" the acknowledgement (confirmation) if that's what you're asking.  I believe the intent is that the `Error` returned in the `completion` block should contain instruction to the user for how to resolve the problem.  If the PumpManager needs to "re-confirm" it, that's up to it to do.  Does that answer your question?

2022-03-24 14:19 UTC, nhamming commented
@rickpasetto Yes, I believe it answers my question. Follow up question, does the coastal pump manager do what it needs to do to confirm alerts with the pump after the pump reconnect?

2022-03-24 14:23 UTC, nhamming commented
@rickpasetto another follow up question. Given that the acknowledgement of the alert has failed, does the alert store mark this alert as acknowledged? If it is not marked as acknowledged, then this alert would be replayed at some point, correct?

2022-03-24 19:04 UTC, nhamming requested changes

2022-03-24 19:04 UTC, nhamming commented on Loop/Managers/Alerts/AlertManager.swift
> -            message = String(format: NSLocalizedString("%1$@ is unable to clear the alert from your device", comment: "Message for alert shown when alert acknowledgement fails for a device, and the d
I suggest we remove `presentAcknowledgementFailedAlert` and rename `acknowledgeAlert` -> `alertAcknowledged`

2022-03-24 19:09 UTC, nhamming approved these changes
Unblocking based on comment ^. Making a new Loop ticket

2022-03-24 19:54 UTC, merged