[LOOP-4289] Critical alert modal update
tidepool-org/Loop pull request #525
Opened 2022-09-08 15:51 UTC by nhamming

https://tidepool.atlassian.net/browse/LOOP-4289

This update include:
- navigating directly to settings from the modal
- copy update

2022-09-08 15:53 UTC, nhamming commented
@ps2 Looking for an initial review of the concept. 

Summary is that the `AlertPermissionsChecker` is now truly just a checker and reports to its delegate. The delegate (`AlertManager`) is responsible to handling the conditions. This allows the `AlertManager` to add a 'Go To Settings" button when the user has adjusted notification permissions in an undesirable way.

2022-09-12 16:18 UTC, ps2 requested changes
I think some naming needs to be clarified, and I would suggest keeping alert definitions on the class that has the responsibility for checking the condition.

2022-09-12 16:18 UTC, ps2 commented on Loop/Managers/Alerts/AlertManager.swift
> +    private static let riskMitigatingAlertIdentifier = Alert.Identifier(managerIdentifier: "LoopAppManager", alertIdentifier: "riskMitigatingAlert")
"risk mitigating alert" is probably too generic.  All alerts are mitigating risks. This alert should be something like "UnsafeNotificationSettingsAlert" , or something along those lines.

2022-09-12 16:18 UTC, ps2 commented on Loop/Managers/AlertPermissionsChecker.swift
> +        // TODO with iOS 16 this API changes to UIApplication.openNotificationSettingsURLString
👍

2022-09-12 16:18 UTC, ps2 commented on Loop/Managers/AlertPermissionsChecker.swift
> -fileprivate extension AlertPermissionsChecker {
Moving the definition of these particular alerts to AlertManager seems like a step backwards in terms of separation of responsibilities. 

I think it makes sense for this class to delegate to AlertManager for issuance, retraction, and general management of these alerts, but the definition/content of the alerts themselves is nice to keep close to the logic that determines the conditions.  Like we have DeviceManagers define the alert content and evaluate the conditions under which to issue/retract, but they delegate to something else for issuance/retraction.

I know the AlertManager *does* have some alert definitions, and some condition evaluation logic for Loop not Looping alerts and Bluetooth disabled alerts, but I feel the same about those; it'd probably be cleaner (and more testable) if those were split out as well.  In this case, we already have a "Checker" class split out, so it feels right to keep the alert definition and condition logic in this class. The seam between this class and the AlertManager could then just be the `AlertIssuer` protocol?

2022-09-12 18:10 UTC, ps2 approved these changes
LGTM. Just wanting to get actions added to Alerts. We've been pushing that out a long time, but it's probably not a huge lift, if we do it minimally (titles + action identifiers).

2022-09-12 18:10 UTC, ps2 commented on Loop/View Controllers/StatusTableViewController.swift
> +            contentConfig.secondaryText = "Enable Critical Alerts\nMore text to see how line wrapping works\nEven more text"
Looks like debug text?

2022-09-12 18:10 UTC, ps2 commented on Loop/Managers/Alerts/AlertManager.swift
> +                self?.acknowledgeAlert(identifier: AlertPermissionsChecker.unsafeNotificationPermissionsAlertIdentifier)
We really should be adding actions to our Alert model for this. I'm guessing you're not doing that for expediency in this case.

2022-09-14 08:11 UTC, merged