[LOOP-4649] Loop Marketing Demo
tidepool-org/Loop pull request #576
Opened 2023-06-12 22:17 UTC by Camji55

https://tidepool.atlassian.net/browse/LOOP-4649

2023-06-13 01:47 UTC, ArwainK approved these changes

2023-06-13 09:07 UTC, nhamming commented on Loop/Plugins/PluginManager.swift
> +    }
Could this use `availableServices` to search for TidepoolSupport instead of handling the UserDefaults search?

2023-06-13 14:34 UTC, ps2 requested changes

2023-06-13 14:34 UTC, ps2 commented on Loop/Plugins/PluginManager.swift
> +import TidepoolSupport
Loop must not link in TidepoolSupport.

2023-06-13 14:34 UTC, ps2 commented on Loop/Plugins/PluginManager.swift
> +import TidepoolSupport
You could add a new generic SupportUI method to let any support mask out devices.

2023-06-15 17:43 UTC, Camji55 commented on Loop/View Models/SettingsViewModel.swift
> +    var showDeleteTestData: Bool {
Thinking it might make sense to rename this to `hideDeleteTestData`. Any opinions?

2023-06-15 17:55 UTC, ps2 commented
I'm not sure the assumption that static plugins == simulator plugins will hold, or that services will only filter on simulator vs non-simulator.  Maybe it would be better to just have the service filter on device identifier?  Seems more flexible, and avoids some assumptions.

2023-06-15 19:24 UTC, ps2 approved these changes
LGTM

2023-06-15 21:50 UTC, merged