[PAL-471] allow manual glucose entry when recommendManualGlucoseEntry is presented
tidepool-org/Loop pull request #624
Opened 2024-03-19 19:32 UTC by nhamming

https://tidepool.atlassian.net/browse/PAL-471

2024-03-19 19:41 UTC, Camji55 approved these changes

2024-03-19 23:38 UTC, ps2 requested changes
I think the manual glucose entry view toggle should be based on the lack of cgm data more directly.

2024-03-19 23:38 UTC, ps2 commented on Loop/View Controllers/StatusTableViewController.swift
> +            let viewModel = CarbEntryViewModel(delegate: loopManager, enableManualGlucoseEntry: .recommendManualGlucoseEntry == statusRowMode)
It's a little indirect to enable the glucose entry view based on `statusRowMode`.  If statusRowMode had a higher priority status available, like bolusing, but we were still in a situation without cgm data, I would expect the manual glucose entry view to still show up.

2024-03-20 13:32 UTC, ps2 approved these changes
LGTM! Just maybe a little nit.

2024-03-20 13:32 UTC, ps2 commented on Loop/View Controllers/StatusTableViewController.swift
> +    private enum StatusRowMode: Equatable {
Is this still needed?

2024-03-20 14:13 UTC, nhamming commented on Loop/View Controllers/StatusTableViewController.swift
> +    private enum StatusRowMode: Equatable {
thanks! good catch

2024-03-20 15:27 UTC, merged