[LOOP-4945] remove stale glucose timer from CGM status HUD view
tidepool-org/Loop pull request #699
Opened 2024-09-04 08:49 UTC by nhamming

https://tidepool.atlassian.net/browse/LOOP-4945

2024-09-04 16:29 UTC, nhamming commented on Loop/View Controllers/StatusTableViewController.swift
> +        hudView?.cgmStatusHUD.isGlucoseValueCurrent = !deviceManager.isGlucoseValueStale
note that this func is called with state changes to the CGM and Pump managers.

2024-09-04 16:46 UTC, ps2 requested changes
I think there is a risk here of the CGM Manager not getting an update, and not reporting to Loop in a timely manner, and then Loop keeping an old value on display. Staleness and signal loss may be two separate things, I think.  On the watch, or widgets, for example, data might become stale due to other factors outside of just CGM signal loss. I think it might be better to keep the idea of staleness in the pill, for safety, and if there are timing issues with the CGM detecting actual signal loss to the ble sensor, as compared to the time that Loop decides staleness, then let's fix that (either by making the staleness period longer, or by making the signal loss activation more timely).

2024-09-04 16:46 UTC, ps2 commented on LoopUI/ViewModel/CGMStatusHUDViewModel.swift
> +    var isGlucoseValueCurrent: Bool = true
Would prefer to keep the terminology as "stale", rather than "current".  The "current" bg could be stale.

2024-09-05 20:19 UTC, ps2 reviewed
So there is a lot going on here...
* Removal of today widget: 👍 
* Moving timer code from cgm pill to status view: I'm not understanding why this change is made; seems to be worse from a separation of concerns standpoint: the status table view controller is already bloated (2k lines!) with logic that should probably be moved into the things it contains, so it can be more of a simple container.
* Are there other logic changes? What is fixing the core issue described in the ticket? I'm not seeing it.

2024-09-06 08:50 UTC, nhamming commented
@ps2 responded in slack. I thought we already discussed those points and these changes were related to the outcomes of that discussion.

2024-09-06 16:27 UTC, ps2 approved these changes
LGTM! Just a question about starting the staleness timer on startup.

2024-09-06 16:27 UTC, ps2 commented on Loop/Managers/LoopDataManager.swift
> +                    self.restartGlucoseValueStalenessTimer()
Should also start the timer on app start, I think.  I didn't see that happening, but maybe I missed it?

2024-09-06 19:30 UTC, merged