Clear pending "loop not looping" notification requests
tidepool-org/Loop pull request #88
Opened 2020-05-14 19:38 UTC by rickpasetto

Opening this draft PR as a means of asking @ps2 a question: Pete, shouldn't the future pending loop-not-looping notification requests be cleared on every loop iteration as well as delivered ones.  Otherwise...isn't there a race condition where a UserNotification is delivered, then cleared when a loop iteration happens?  Also, isn't this just loading up UserNotificationCenter's future pending alerts?  Note: `clearPendingNotificationRequests()` does not seem to ever be called anywhere.  (Also: it is implemented incorrectly...)

2020-05-18 16:54 UTC, rickpasetto commented
Haven't heard from @ps2 so I'll "un-draft" this.

2020-05-18 18:18 UTC, ps2 commented
"If you use the same identifier when scheduling a new notification, the system removes the previously scheduled notification with that identifier and replaces it with the new one."

2020-05-18 18:21 UTC, ps2 requested changes
I don't believe the changes in this PR are necessary. We could take the change for cleaning up the unused `clearPendingNotificationRequests` if desired.

2020-05-18 19:04 UTC, rickpasetto commented
Hm...okay, I see that quote now (took me a while to find it) in https://developer.apple.com/documentation/usernotifications/unnotificationrequest/1649634-identifier.
If that's the case, then why schedule four  (at `[20, 40, 60, 120]` minutes) ?  Won't they just collapse into one?

2020-05-18 19:41 UTC, ps2 commented
No, because the identifier has the failure interval in it: 
```
identifier: "\(LoopNotificationCategory.loopNotRunning.rawValue)\(failureInterval)",
```

2020-05-18 19:50 UTC, rickpasetto commented
Ahhhhh...clever!  Ok...I'll just change this PR to be the trivial removal of the unused `clearPendingNotificationRequests`

2020-05-21 14:38 UTC, ps2 approved these changes

2020-05-21 18:43 UTC, merged